core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
rebase.autosquash=true
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager
user.name=Danilo Molina Morales
user.email=danilo.molina.morales@gmail.com
user.emal=danilo.molina.morales@gmail.com
user.username=DaniloMolinaM
gui.recentrepo=C:/GitProyecto
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/DaniloMolinaM/patchwork
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.gh-pages.remote=origin
branch.gh-pages.merge=refs/heads/gh-pages
remote.upstream.url=https://github.com/jlord/patchwork.git
remote.upstream.fetch=+refs/heads/*:refs/remotes/upstream/*
